### ISSUE TITLE
Dfficulty finding goto-cc in package cbmc

### ISSUE THREAD

**Issue by marriv99** [model-checking/cbmc-training#10]
I proceeded to install cbmc on my Windows machine following your guide. Subsequently when running the unit-testing I cannot find the goto-cc file in the /cbmc/bin. The files present in /bin are cbmc.exe, cprover.exe, crangler.exe, goto-analyzer.exe, goto-cl.exe, goto-diff.exe, goto-harness.exe, goto-inspect.exe, goto -instrument.exe, goto-synthesizer.exe, janalyzer.exe, jbmc.exe, jdiff.exe, symtab2gb.exe.

**Comment by tautschnig** [comment]
Thank you for your report, we should caveat our documentation to state that, on Windows, you want to use `goto-cl` in place of `goto-cc`.
