### ISSUE TITLE
The FreeRTOS Kernel heap-allocation tutorial requires more unwinding for the proofs to go through

### ISSUE THREAD

**Issue by akshayutture** [model-checking/cbmc-training#2]
For the tutorial, the default unwinding length of 1 gives an unwinding assertion failure. Even 2 failed. An undwinding length of 5 allowed all proofs to go through without any unwinding assertion failure.

(Maybe this is correlated with #3  ? Maybe the default unwind length was sufficient when the tutorial was written but then the kernel code changed?)

**Comment by markrtuttle** [comment]
Resolved with https://github.com/model-checking/cbmc-training/pull/6
