### ISSUE TITLE
Maybe clone a specific version of the kernel for the FreeRTOS heap tutorial?

### ISSUE THREAD

**Issue by akshayutture** [model-checking/cbmc-training#3]
Changes in the FreeRTOS kernel could result in the output not matching exactly what is listed in the tutorial.

For example, when asked 'what is the function name', and we type 'pvPortMalloc', I see 13 options instead of the 11 mentioned in the tutorial. And the correct source file number was at number 11 instead of the number 9 which was listed in the tutorial.

**Comment by markrtuttle** [comment]
Resolved by https://github.com/model-checking/cbmc-training/pull/6
